[sae]
n_latent = 4096
k = 64
batch_size = 8192
lr = 3e-4
num_epochs = 50
aux_k = 512
aux_beta = 0.03125  # 1/32
dead_threshold = 50000
data_dir = "/ocean/projects/atm170004p/lxu5/ConvAE/EVAL_DATA/SNAPSHOTS/CAEwCP_TrP_A_TrS_10000_KS_5_LN_5_LD_256_BS_2_LR_0.001_WD_1e-06_DP_0.0_EN_1500_SD_42/ep_best_pi_0/TeP_A_10000_TD_0.2_SAE/"
layer_name = "E1"
output_dir = "/ocean/projects/atm170004p/jshen6/cae_sae/"
use_wandb = false
seed = 42
log_every = 100
